### ISSUE TITLE
Problem on running the project

### ISSUE THREAD

**Issue by hirockstar** [CryogenicPlanet/cryogenicplanet.github.io#52]
i try to run your project on my local im getting these errors how i can fix them.
Can you help us to fix it? please
![Screenshot 2022-11-28 201730](https://user-images.githubusercontent.com/45270927/204313419-66439e47-f5d3-4d3b-adff-06ce3415bb27.png)

**Comment by hirockstar** [comment]
@CryogenicPlanet still no update bro 😢

**Comment by CryogenicPlanet** [comment]
Read the damn terminal, the error is clearly there very clearly 🤦

**Comment by hirockstar** [comment]
but i don't know how to fix it 🙂
