### ISSUE TITLE
demo.env

### ISSUE THREAD

**Issue by hirockstar** [CryogenicPlanet/cryogenicplanet.github.io#53]
we need demo.env file of your project where we can get that??

**Comment by CryogenicPlanet** [comment]
Not sure what you really want to do with this, but this is not meant to be auto run as a project - it is a personal website, it is meant to be very custom. Feel free to take parts of the code or use things you find interesting but you aren't meant to blindly clone this repo.

That said if you are just looking for env variables a quick search will help solve that https://github.com/CryogenicPlanet/cryogenicplanet.github.io/search?q=process.env

The notion envs are very specific to my notion, more docs on that here https://github.com/splitbee/notion-api-worker

Would very much recommend putting in some work to try to google what these variables or to use some intuition to guess what they could be - nothing particularly complex here
